### Obtener todos los equipos
GET http://localhost:3000/api/equipos

### Crear equipo
# @name createEquipo
POST http://localhost:3000/api/equipos
Content-Type: application/json

{
  "nombre": "Team Phoenix",
  "capitan": 1,
  "jugadores": [1, 2]
}

### Obtener equipo específico
@equipoId = {{createEquipo.response.body.data.id}}
GET http://localhost:3000/api/equipos/{{equipoId}}