### Obtener todos los torneos
GET http://localhost:3000/api/torneos

### Crear un torneo
# @name createEsl
POST http://localhost:3000/api/torneos
Content-Type: application/json

{
    "nombre": "ESL Pro League Season 25 - CS2",
    "descripcionReglas": "Formato: 16 equipos, grupos GSL + eliminatorias BO3...",
    "cantidadJugadores": 16,
    "fechaInicio": "2024-06-15T18:00:00", 
    "fechaFin": "2024-06-30T23:00:00",
    "fechaInicioIns": "2024-04-01T00:00:00",
    "fechaFinIns": "2024-05-31T23:59:00",
    "resultado": "Team Vitality campeón (3-1 vs FaZe Clan)",
    "region": "Global",
    "estado": "finalizado"
}

### ID
@id = {{createEsl.response.body.data.id}}

### Obtener un torneo
GET http://localhost:3000/api/torneos/{{id}}

### Modificar un torneo (Entero)
PUT http://localhost:3000/api/torneos/{{id}}
Content-Type: application/json

{
    "nombre": "Worlds Championship 2025",
    "descripcionReglas": "Formato: Fase de grupos + eliminatorias BO5...",
    "cantidadJugadores": 16,
    "fechaInicio": "2024-10-01T15:00:00",
    "fechaFin": "2024-11-15T22:00:00",
    "fechaInicioIns": "2024-07-01T00:00:00",
    "fechaFinIns": "2024-09-15T23:59:00",
    "resultado": "Pendiente",
    "region": "Global",
    "estado": "En curso"
}

### Agregar un torneo
POST http://localhost:3000/api/torneos
Content-Type: application/json

{
    "nombre": "WPL Pro League - Valorant",
    "descripcionReglas": "Formato: 8 equipos",
    "cantidadJugadores": 16,
    "fechaInicio": "2024-07-15T18:00:00", 
    "fechaFin": "2024-07-30T23:00:00",
    "fechaInicioIns": "2024-05-01T00:00:00",
    "fechaFinIns": "2024-06-31T23:59:00",
    "resultado": "Team Fnatic campeón (3-1 vs Navi)",
    "region": "Global",
    "estado": "finalizado"
}

### Agregar un torneo
# @name createTorneoToDelete
POST http://localhost:3000/api/torneos
Content-Type: application/json

{
    "nombre": "Royale con queso",
    "descripcionReglas": "Formato: 1vs1",
    "cantidadJugadores": 10,
    "fechaInicio": "2024-12-12T18:00:00", 
    "fechaFin": "2024-12-12T23:00:00",
    "fechaInicioIns": "2024-10-01T00:00:00",
    "fechaFinIns": "2024-10-20T23:59:00",
    "resultado": "Undefined",
    "region": "Global",
    "estado": "En curso"
}

### Eliminar un torneo
@idToDelete = {{createTorneoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/torneos/{{idToDelete}}

### Actualizar parte de un torneo
PATCH http://localhost:3000/api/torneos/{{idToDelete}}
Content-Type: application/json

{
    "resultado": "T1 campeón (3-2 vs Weibo Gaming)",
    "estado": "Finalizado"
}

### Eliminar un torneo
DELETE http://localhost:3000/api/torneos/{{idToDelete}}
