### Inscribir EQUIPO en torneo por equipos
# @name inscribirEquipo
POST http://localhost:3000/api/torneos/{{torneoEquiposId}}/inscribir
Content-Type: application/json

{
  "equipoId": {{equipoId}}
}

### Inscribir USUARIO INDIVIDUAL en torneo individual
# @name inscribirIndividual
POST http://localhost:3000/api/torneos/{{torneoIndividualId}}/inscribir
Content-Type: application/json

{
  "usuarioId": {{usuario3Id}}
}