### Obtener todas las plataformas
GET http://localhost:3000/api/plataforma/

### Crear plataforma
# @name createPlataforma
POST http://localhost:3000/api/plataforma/
Content-Type: application/json

{
  "nombre": "PC",
  "descripcion": "Plataforma de computadora personal"
}

### Obtener plataforma específica
@plataformaId = {{createPlataforma.response.body.data.id}}
GET http://localhost:3000/api/plataforma/{{plataformaId}}