### Obtener todos los juegos
GET http://localhost:3000/api/juego/

### Crear juego
# @name createJuego
POST http://localhost:3000/api/juego/
Content-Type: application/json

{
  "nombre": "Valorant",
  "descripcion": "Shooter táctico 5v5",
  "tipoDeJuego": 1,
  "plataformas": [1]
}

### Crear juego individual
# @name createJuego
POST http://localhost:3000/api/juego/
Content-Type: application/json

{
  "nombre": "Clash Royale",
  "descripcion": "Juego de cartas",
  "tipoDeJuego": 2,
  "plataformas": [1]
}

### Obtener juego específico
@juegoId = {{createJuego.response.body.data.id}}
GET http://localhost:3000/api/juego/{{juegoId}}