### get 
GET http://localhost:3000/api/tipoDeJuego/

### post
# @name createTipoDeJuego
POST http://localhost:3000/api/tipoDeJuego/
Content-Type: application/json

{
  "nombre":"Accion",
  "descripcion":"Juegos donde hay accion"
}

### put
@id={{createTipoDeJuego.response.body.data.id}}
PUT http://localhost:3000/api/tipoDeJuego/{{id}}
Content-Type: application/json

{
  "nombre":"Accion",
  "descripcion":"Juegos donde hay mucha accion"
}

### get one
GET  http://localhost:3000/api/tipoDeJuego/{{id}}

### post 
POST http://localhost:3000/api/tipoDeJuego/
Content-Type: application/json

{
  "nombre":"Terror",
  "descripcion":"Juegos donde hay Terror"
}

### delete
DELETE  http://localhost:3000/api/tipoDeJuego/{{id}}



